name: Draft Release
on:
  push:
    tags:
    - '*.*.*'
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

jobs:
  build_and_create_release:
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-latest
    env:
      Solution_Name: MemoGenerator.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Debug
      run: dir MemoGenerator\bin\x64\Release\net6.0-windows10.0.18362.0

    - name: Upload artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        name: MemoGenerator-${{ github.ref_name }}-${{ matrix.platform }}
    
        # A file, directory or wildcard pattern that describes what to upload
        path: MemoGenerator/bin/${{ matrix.platform }}/Release/net6.0-windows10.0.18362.0/win10-${{ matrix.platform }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.upload-artifact.outputs.artifact-url }}
        draft: true
